# .pre-commit-config.yaml
# jcarlin@hmc.edu 25 April 2025
# Pre-commit hook configuration file for cvw-arch-verif

# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: "4.0.0"
exclude: "^_archive/"
repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
        exclude: \.adoc$ # sections titles Level 6 "=======" get flagged otherwise
      - id: check-json
      - id: check-toml
      - id: check-yaml

  # Ruff Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # Pyright Python type checker
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]

  # Ensure uv lock file is up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.4
    hooks:
      - id: uv-lock

  # Use spaces, not tabs
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude: '.*\.(diff|dump|patch|svg|mk)|Makefile*'

  # Prettier for json, yaml, markdown, etc. formatting
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier

  # Avoid common misspellings
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  # clang-format for assembly files
  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: "v19.1.7"
  #   hooks:
  #     - id: clang-format
